# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kristina Donaldson's Site
name: Kristina Donaldson's Site
owner: K DONALDSON
email: donaldsonkristinar@yahoo.com

description: >- # this means to ignore newlines until "baseurl:"
  Bibliophile, biophile, and outdoor enthusiast with drive to make the world a 
  better place through technology and scientific advancement. I'm only starting 
  out but hope one day to make a substancial contribution to society. 
baseurl: "/kdonaldsonsite" # the subpath of your site, e.g. /blog
url: "" 

permalink: /blog/:title
github_username:  krdonaldson

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true

exclude:
  - LICENSE
  - README.md
  - html-templates

markdown: kramdown




# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
